[2025-02-14T05:53:11.837+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-14T05:53:11.844+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_dag.run_etl_pipeline manual__2025-02-14T05:53:10.833280+00:00 [queued]>
[2025-02-14T05:53:11.848+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_dag.run_etl_pipeline manual__2025-02-14T05:53:10.833280+00:00 [queued]>
[2025-02-14T05:53:11.848+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-14T05:53:11.856+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): run_etl_pipeline> on 2025-02-14 05:53:10.833280+00:00
[2025-02-14T05:53:11.869+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_dag', 'run_etl_pipeline', 'manual__2025-02-14T05:53:10.833280+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_dag.py', '--cfg-path', '/tmp/tmpq_ztcirm']
[2025-02-14T05:53:11.873+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask run_etl_pipeline
[2025-02-14T05:53:11.874+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=233) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-14T05:53:11.874+0000] {standard_task_runner.py:72} INFO - Started process 234 to run task
[2025-02-14T05:53:11.897+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline_dag.run_etl_pipeline manual__2025-02-14T05:53:10.833280+00:00 [running]> on host f5fadfece92c
[2025-02-14T05:53:11.930+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline_dag' AIRFLOW_CTX_TASK_ID='run_etl_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T05:53:10.833280+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-14T05:53:10.833280+00:00'
[2025-02-14T05:53:11.930+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-14T05:53:11.937+0000] {logging_mixin.py:190} INFO - Starting ETL pipeline...
[2025-02-14T05:53:11.937+0000] {logging_mixin.py:190} INFO - Extracting data...
[2025-02-14T05:53:11.941+0000] {logging_mixin.py:190} INFO - ETL pipeline failed: (psycopg2.OperationalError) connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-02-14T05:53:11.942+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-14T05:53:11.945+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-14T05:53:11.945+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=etl_pipeline_dag, task_id=run_etl_pipeline, run_id=manual__2025-02-14T05:53:10.833280+00:00, execution_date=20250214T055310, start_date=20250214T055311, end_date=20250214T055311
[2025-02-14T05:53:11.976+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-14T05:53:11.981+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-14T05:53:11.982+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
